sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=javascript-automation
    - secure: >-
        C6xMkv4dS704NY9phwBbghe4t9JqoUgVVEELBK2UgdsqOVwFooYpEhsmh6IQPbUBfJO9u4/rvB5bcyV232MYVZd1ihRabAJqtVX1/r5SSwBzHQt7lLpeLenDc62UoHilj3z0x+MIW/c+JPWgporThtX+dtDxK+b2wF/0gd7bBNoO1o+p1hVILQJYjsFjMrwyDIU8JsWL4+N3ypuXVEnOvyavD1xqKu5H8PcDw2Px+CUgUcaSXsc4XNAZU32ScZ+iji3W1xR9srvRi8++wr4RxJxPsjjQyub7MNuAIprAIfivU9drmUJN9M5iQughd185/HYYMrg9qFVvkWyoFIvrOtj9DCHzZkoHYykob8EGmam0IGs4r05daTGZea9HzIu9wRLc10JvvKVmphGe8Hrhsh4IZF2ew15TJsxvOuRj4EenKqL+jxWQqlD9cd+vSU7kSrCVDNQ/QZJrp18HuWD8dOhlL5Wv4q6C0ooVLLuAcKYYSOvKAKqebftSj9Jv8IbZBRbEbJ8gYZZzckfRzK05Ttffm3Npk9o63UpUhoxqyU19dl51KZac1PcGSaCqktq3xKDG0dkXnKnpHnS6rnRVG/rFpxTcV/mhsXGjX0U0st/HWEN7+v31PA6zQ0XR6uM74GcRMqZrHiCzqq6uiUtUptQX/NN9YWvbJhQ57Fi7510=
    - secure: >-
        cRyOw0MsTTvazTuN73W6A+YFRh6mK3RMA4c/KiKPZoTHus+VLn+jyC7DAt8VDPFXcjimvZf3IZHeDnWbR+IcV3vflSPBqPL9z/phyvegRbZg3stFdn6I82lqKXzIzz66Uyn1CIv7oG5Or7ROhPcpLEIvtEgrJOgmYDXWMsaaPtXKCgy3Pbhg6Tb13I3ySba+w/uTBZw+sS/GJ62729r3LNMXKX9x/ae6cTA53CQl+kTbHR1pIsVq120oyWXm44uJxNNoBL5NKmqG24A6JAw8GyXgidgyYHc7qPjntlaY1W55rP05st0JO7VTolEF66VO3Xb4DVD9BaBZG8635SMCefQHccfxgynyiTWHni68uVnL30AA0/dbODv/uruYuqeXOMhkgBfeI1PbSrY8EOa1YBearx1e1AWJfepsI5OYjWMLpQONwsBC0zQcIDSnxQkDZdvXxzag59scJwWBgNH88CxCuJ8ajY+NLB6AnxyiSQglPcQxtJdcwOainP9ocUtoY29+1aFRrNK0EXbkWqYAhCoueH0v5IjOmnD6Bf5fa6sVGAba6H5GwMrVJq1N7URfBd6qyWfgbJ2jL+n29ibcGrE//84R/QXmLBKJhskDLJfI5GkxN/fXx2W1LIgmiYGEiRHnoUbuObr+j6kwoKP98NwNBiNWT8yxAwiVlglFCIo=
script:
  - npm run test
notifications:
  webhooks: 'http://ec2-54-234-52-201.compute-1.amazonaws.com/automation/ci/build'
